### ISSUE TITLE
requirements for transformers link in readme gives 404 error

### ISSUE THREAD

**Issue by shankyemcee** [shrimai/Focused-Attention-Improves-Document-Grounded-Generation#4]
The link to the requirements on the readme is broken. Please fix, and provide the complete list of requirements.

**Comment by shrimai** [comment]
You need to basically install transformers version 3.1.0. No additional requirements for this code.

**Comment by shankyemcee** [comment]
It also asked me to install nltk and torch...I think it will help users if a list of requirements are included. Thanks for the response.
